<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CatsAndMouseApi.Tests/**/*.cs" />
    <Content Remove="CatsAndMouseApi.Tests/**/*" />
    <EmbeddedResource Remove="CatsAndMouseApi.Tests/**/*" />
    <None Remove="CatsAndMouseApi.Tests/**/*" />
  </ItemGroup>

</Project>
